/**
 * Step 5: Write updated promise files and create a PR via gh CLI.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { parseArgs } from "node:util";
import { execFileSync } from "node:child_process";
import {
  type Extraction,
  type Match,
  type Update,
  type Promise as PromiseData,
  loadJson,
  validateMatches,
  validateUpdates,
} from "./schemas.ts";

const PROMISES_DIR = new URL("../src/data/promises/", import.meta.url).pathname;
const REPO_ROOT = new URL("../", import.meta.url).pathname;
const MAX_CHANGES = 5;

function git(...args: string[]): string {
  // Use execFileSync with an array — no shell, so arbitrary content in
  // args (commit messages, file paths) cannot be interpreted as shell
  // syntax. Don't switch to execSync with string interpolation.
  return execFileSync("git", args, {
    cwd: REPO_ROOT,
    encoding: "utf-8",
  }).trim();
}

function applyUpdates(updates: Update[]): string[] {
  const today = new Date().toISOString().slice(0, 10);
  const changed: string[] = [];
  for (const update of updates) {
    const path = join(PROMISES_DIR, `${update.promise_id}.json`);
    if (!existsSync(path)) {
      console.error(`Warning: promise file not found: ${path}`);
      continue;
    }

    const promise: PromiseData = JSON.parse(readFileSync(path, "utf-8"));
    if (promise.status === update.new_status) continue;

    if (!promise.updates) promise.updates = [];
    promise.updates.push({
      date: today,
      status: update.new_status,
      reasoning: update.reasoning,
      sources: update.sources.map((value) => ({ value, archive: "" })),
      confidence: update.confidence,
    });
    promise.status = update.new_status;

    writeFileSync(path, JSON.stringify(promise, null, 2) + "\n");
    changed.push(path);
  }
  return changed;
}

function createNewPromises(matches: Match[], extracted: Extraction[]): string[] {
  const created: string[] = [];
  for (const match of matches) {
    if (match.type !== "new") continue;
    if (match.extracted_index >= extracted.length) continue;

    const e = extracted[match.extracted_index];

    // Generate ID from party and promise text
    const partyPrefix = e.politician_or_party
      .split("(")
      .pop()!
      .replace(")", "")
      .trim()
      .toLowerCase()
      .slice(0, 3);
    const slug = e.promise_text
      .slice(0, 50)
      .toLowerCase()
      .replace(/[^a-zåäö0-9 ]/g, "")
      .trim()
      .replace(/\s+/g, "-");
    const promiseId = `${partyPrefix}-${slug}`;

    const promise: PromiseData = {
      id: promiseId,
      name: e.promise_text.slice(0, 100),
      description: e.promise_text,
      party: e.politician_or_party,
      status: "Pågående",
      date: e.date,
      sources: [{ value: e.source_url, archive: "" }],
      tags: [],
      updates: [],
    };

    const path = join(PROMISES_DIR, `${promiseId}.json`);
    writeFileSync(path, JSON.stringify(promise, null, 2) + "\n");
    created.push(path);
  }
  return created;
}

function buildPrBody(updates: Update[], matches: Match[], extracted: Extraction[]): string {
  const lines = ["## Pipeline Update\n"];
  lines.push("Automated changes from the AI promise-tracking pipeline.\n");

  if (updates.length > 0) {
    lines.push("### Status Changes\n");
    for (const u of updates) {
      lines.push(`- **${u.promise_id}**: → ${u.new_status} (${u.confidence} confidence)`);
      lines.push(`  - ${u.reasoning}`);
      for (const src of u.sources) {
        lines.push(`  - Source: ${src}`);
      }
    }
    lines.push("");
  }

  const newCount = matches.filter((m) => m.type === "new").length;
  if (newCount > 0) {
    lines.push(`### New Promises: ${newCount}\n`);
    for (const m of matches) {
      if (m.type === "new" && m.extracted_index < extracted.length) {
        const e = extracted[m.extracted_index];
        lines.push(`- ${e.politician_or_party}: ${e.promise_text.slice(0, 80)}`);
      }
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by the Brutna Löften AI pipeline. Please review all changes carefully.*");
  return lines.join("\n");
}

// --- Main ---

const { values } = parseArgs({
  options: {
    updates: { type: "string", default: "updates.json" },
    matches: { type: "string", default: "matches.json" },
    extracted: { type: "string", default: "extracted.json" },
    "dry-run": { type: "boolean", default: false },
    "max-changes": { type: "string", default: String(MAX_CHANGES) },
  },
});

const maxChanges = parseInt(values["max-changes"]!, 10);
const updates = existsSync(values.updates!)
  ? validateUpdates(loadJson(values.updates!) as unknown[])
  : [];
const matches = existsSync(values.matches!)
  ? validateMatches(loadJson(values.matches!) as unknown[])
  : [];
const extracted = existsSync(values.extracted!)
  ? (loadJson(values.extracted!) as Extraction[])
  : [];

const totalChanges = updates.length + matches.filter((m) => m.type === "new").length;

if (totalChanges === 0) {
  console.error("No changes to apply.");
  process.exit(0);
}

// Anomaly guard
if (totalChanges > maxChanges) {
  console.error(
    `ABORT: ${totalChanges} changes exceeds limit of ${maxChanges}. ` +
      "Review manually or increase --max-changes.",
  );
  process.exit(1);
}

const changed = applyUpdates(updates);
const created = createNewPromises(matches, extracted);
const allFiles = [...changed, ...created];

if (allFiles.length === 0) {
  console.error("No files were modified.");
  process.exit(0);
}

console.error(`Modified ${changed.length} files, created ${created.length} files`);

if (values["dry-run"]) {
  console.error("DRY RUN: skipping git operations");
  process.exit(0);
}

// Create branch and PR
const timestamp = new Date().toISOString().replace(/[T:]/g, "-").slice(0, 19);
const branch = `pipeline/update-${timestamp}`;

git("checkout", "-b", branch);
for (const f of allFiles) {
  git("add", f);
}
// Message is passed as a bare arg to execFileSync, so no manual
// shell-quoting — the wrapping literal quotes the previous version added
// would have become part of the commit message itself.
git("commit", "-m", `pipeline: update promises ${timestamp}`);
git("push", "-u", "origin", branch);

// Create PR via gh CLI. execFileSync with an array of args means the
// PR body (which contains Claude-generated text) is passed to gh as a
// single argv entry and never touches a shell — no injection risk from
// backticks, $, or \ in the reasoning or promise text.
const prBody = buildPrBody(updates, matches, extracted);
const prResult = execFileSync(
  "gh",
  [
    "pr",
    "create",
    "--title",
    `Pipeline: Update promises ${timestamp}`,
    "--body",
    prBody,
  ],
  { cwd: REPO_ROOT, encoding: "utf-8" },
).trim();

console.error(`PR created: ${prResult}`);
